const state={category:'calentado',cart:[],query:'',quizAnswers:[]},PERSONALIZATION_PRICE=3.90;
const icons={calentado:'<svg viewBox="0 0 24 24"><rect x="8" y="9" width="8" height="13" rx="2"/><path d="M10 6c-2-2 1-3 0-5M13 6c-2-2 1-3 0-5M16 6c-2-2 1-3 0-5"/></svg>',vapeo:'<svg viewBox="0 0 24 24"><path d="M9 5h6v4H9zM8 9h8v12H8zM10 13h4M10 18h4"/></svg>',pouches:'<svg viewBox="0 0 24 24"><path d="M4 7l15-2 1 14-15 2zM7 9c3 2 6 2 9 0"/></svg>',cigarrillos:'<svg viewBox="0 0 24 24"><path d="M3 14h16M3 14v4h16v-4M15 14v4M8 10c-2-2 1-3 0-5"/></svg>',accesorios:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M12 3v3M12 18v3M3 12h3M18 12h3M5.6 5.6l2.1 2.1M16.3 16.3l2.1 2.1M18.4 5.6l-2.1 2.1M7.7 16.3l-2.1 2.1"/><circle cx="12" cy="12" r="8"/></svg>'};
const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n||0)+' €',escapeHTML=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
const photo=(p,color)=>color&&p.imageVariants?.[color]||p.image;
state.prize=null;
const PRIZES=[{id:'personalization',label:'Personalización gratis',detail:'El grabado de un accesorio no tendrá coste.'},{id:'accessory',label:'5% en accesorios',detail:'Descuento automático sobre accesorios.'},{id:'direct',label:'2 € de descuento',detail:'Descuento directo en tu selección.'},{id:'shipping',label:'Detalle JTI',detail:'Recoge un detalle en el mostrador.'}];
function prizeDiscount(){if(!state.prize)return 0;if(state.prize.id==='personalization')return state.cart.reduce((sum,item)=>sum+Number(item.personalizationPrice||0),0);if(state.prize.id==='accessory')return state.cart.reduce((sum,item)=>{const product=PRODUCTS.find(candidate=>candidate.id===item.id);return sum+(product?.cat==='accesorios'?(product.price||0)*.05:0);},0);if(state.prize.id==='direct')return state.cart.length?2:0;return 0;}
function renderUpsell(id){const choices=(BUNDLES[id]||[]).map(itemId=>PRODUCTS.find(product=>product.id===itemId)).filter(product=>product&&photo(product)&&!state.cart.some(item=>item.id===product.id));if(!choices.length)return;const panel=document.createElement('section');panel.className='upsell-panel';panel.innerHTML=`<small>COMPLETA TU SELECCIÓN</small><div>${choices.slice(0,2).map(product=>`<button data-id="${product.id}"><img src="${encodeURI(photo(product))}" alt=""><span><b>${product.name}</b><em>${money(product.price)}</em></span><i>+</i></button>`).join('')}</div>`;$('add-product').before(panel);panel.querySelectorAll('button').forEach(button=>button.onclick=()=>{const product=PRODUCTS.find(item=>item.id===button.dataset.id);state.cart.push({id:product.id});updateCart();button.disabled=true;button.querySelector('i').textContent='✓';toast('Producto complementario añadido');});}
function openRoulette(){const box=$('roulette-card');const won=state.prize;if(won){box.innerHTML=`<button class="roulette-close" id="close-roulette">×</button><small>PREMIO ACTIVO</small><h2>${won.label}</h2><p>${won.detail}</p><button class="roulette-claim" id="close-roulette">Seguir explorando</button>`;}else{box.innerHTML=`<button class="roulette-close" id="close-roulette">×</button><small>GIRA Y GANA</small><h2>Tu sorpresa JTI</h2><div class="prize-wheel" id="prize-wheel"><span>5%</span><span>GRATIS</span><span>2 €</span><span>JTI</span></div><p>Una oportunidad por visita.</p><button class="roulette-claim" id="spin-roulette">Girar la ruleta</button>`;}$('roulette-modal').classList.add('show');$('close-roulette').onclick=()=>$('roulette-modal').classList.remove('show');const spin=$('spin-roulette');if(spin)spin.onclick=()=>{spin.disabled=true;$('prize-wheel').classList.add('spinning');setTimeout(()=>{state.prize=PRIZES[Math.floor(Math.random()*PRIZES.length)];updateCart();openRoulette();},1300);};}
const originalOpenProduct=openProduct;openProduct=id=>{originalOpenProduct(id);renderUpsell(id);};
const originalUpdateCart=updateCart;updateCart=()=>{originalUpdateCart();const subtotal=state.cart.reduce((sum,item)=>sum+(PRODUCTS.find(product=>product.id===item.id)?.price||0)+Number(item.personalizationPrice||0),0);$('cart-total').textContent=money(Math.max(0,subtotal-prizeDiscount()));};
const originalCartTotal=cartTotal;cartTotal=()=>Math.max(0,originalCartTotal()-prizeDiscount());
const originalEnter=enter;enter=()=>{originalEnter();$('open-roulette').onclick=openRoulette;};
const listed=()=>PRODUCTS.filter(p=>p.cat===state.category&&photo(p)&&(`${p.name} ${p.brand}`).toLowerCase().includes(state.query));
function renderNav(){ $('category-nav').innerHTML=CATEGORIES.map(c=>`<button class="category ${state.category===c.id?'is-active':''}" data-cat="${c.id}"><span>${icons[c.id]}</span><b>${c.name}</b></button>`).join('');$('category-nav').querySelectorAll('button').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;render();}); }
function card(p){return `<article class="product-card shape-${p.shape}" data-id="${p.id}"><div class="product-stage"><div class="stage-copy"><b>${p.brand}</b><span></span><small>${p.cat==='calentado'?'REFINED BY DESIGN':'DESCUBRE LA COLECCIÓN'}</small></div><img src="${encodeURI(photo(p))}" alt="${p.name}"></div><div class="product-info"><small>${p.brand}</small><h3>${p.name}</h3><div><strong>${money(p.price)}</strong><button class="view-product">Ver <i>›</i></button></div></div></article>`;}
function render(){renderNav();const p=listed();$('product-grid').innerHTML=p.length?p.map(card).join(''):'<p class="empty">No hay productos disponibles en esta categoría.</p>';$('product-grid').querySelectorAll('.product-card').forEach(el=>el.onclick=()=>openProduct(el.dataset.id));}
function openProduct(id){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;let selectedColor=p.swatches?.[0]||p.color;const engravingColor=color=>{const hex=(color||'#1c1c1e').replace('#','');const n=parseInt(hex.length===3?hex.split('').map(x=>x+x).join(''):hex,16),l=((n>>16)*.299+((n>>8)&255)*.587+(n&255)*.114)/255;return l>.62?'#0b4440':'#f4d58e';};const personalization=p.customizable?`<label class="personalization"><span>Personaliza tu accesorio <b>+${money(PERSONALIZATION_PRICE)}</b></span><input id="personalization-input" type="text" maxlength="10" placeholder="Tu nombre" autocomplete="off"><small>Máximo 10 caracteres · vista previa de grabado</small></label>`:'';$('modal-card').className=`modal-card shape-${p.shape}`;$('modal-card').innerHTML=`<button class="close" id="close-modal">×</button><div class="modal-visual"><div class="custom-preview template-${p.customTemplate||'none'}"><img id="modal-image" src="${encodeURI(photo(p,selectedColor))}" alt="${p.name}">${p.customizable?'<span id="personalization-preview" aria-hidden="true"></span>':''}</div></div><div class="modal-info"><small>${p.brand}</small><h2>${p.name}</h2><p>${p.desc}</p><strong id="modal-price">${money(p.price)}</strong>${p.swatches?`<div class="swatches">${p.swatches.map((c,i)=>`<button class="swatch ${i===0?'selected':''}" style="--swatch:${c}" data-color="${c}" aria-label="Color"></button>`).join('')}</div>`:''}${personalization}<button class="add-button" id="add-product">Añadir a mi selección</button></div>`;$('product-modal').classList.add('show');$('close-modal').onclick=closeModal;const input=$('personalization-input'),preview=$('personalization-preview'),modalPrice=$('modal-price');const refreshPersonalization=()=>{const text=input?.value.trim()||'';if(preview){preview.textContent=text;preview.style.setProperty('--engraving',engravingColor(selectedColor));}modalPrice.textContent=money(p.price+(text?PERSONALIZATION_PRICE:0));};$('modal-card').querySelectorAll('.swatch').forEach(s=>s.onclick=()=>{selectedColor=s.dataset.color;$('modal-card').querySelectorAll('.swatch').forEach(x=>x.classList.remove('selected'));s.classList.add('selected');$('modal-image').src=encodeURI(photo(p,selectedColor));refreshPersonalization();});if(input){input.oninput=refreshPersonalization;refreshPersonalization();}$('add-product').onclick=()=>{const personalization=input?.value.trim()||'';state.cart.push({id:p.id,personalization,personalizationPrice:personalization?PERSONALIZATION_PRICE:0});updateCart();closeModal();toast(`${p.name} añadido`);};}
function closeModal(){$('product-modal').classList.remove('show');}function updateCart(){const total=state.cart.reduce((n,i)=>n+(PRODUCTS.find(p=>p.id===i.id)?.price||0),0);$('selection-count').textContent=`${state.cart.length} producto${state.cart.length===1?'':'s'}`;$('cart-total').textContent=money(total);}let timer;function toast(text){const t=$('toast');t.textContent=text;t.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>t.classList.remove('show'),1600);}function enter(){$('age-gate').hidden=true;$('catalogue').hidden=false;render();updateCart();}
const quizSteps=[{question:'¿Qué formato te interesa más?',options:[['Dispositivo de tabaco calentado','calentado'],['Vapeador','vapeo'],['Bolsitas de nicotina','pouches'],['Cigarrillos','cigarrillos']]},{question:'¿Qué estilo buscas?',options:[['Clásico y discreto','clasico'],['Fresco y ligero','fresco'],['Moderno y llamativo','moderno']]},{question:'¿Para qué momento lo buscas?',options:[['Para cualquier momento','cualquier-momento'],['Para una experiencia intensa','intenso'],['Para probar algo nuevo','moderno']]}];
function renderQuiz(step=0){const q=quizSteps[step];$('quiz-card').innerHTML=`<button class="quiz-close" id="close-quiz">×</button><small>PREGUNTA ${step+1} DE ${quizSteps.length}</small><h2>${q.question}</h2><div class="quiz-options">${q.options.map(([label,value])=>`<button data-value="${value}">${label}<span>›</span></button>`).join('')}</div>`;$('close-quiz').onclick=closeQuiz;$('quiz-card').querySelectorAll('.quiz-options button').forEach(b=>b.onclick=()=>{state.quizAnswers[step]=b.dataset.value;if(step<quizSteps.length-1)renderQuiz(step+1);else showRecommendation();});}
function openQuiz(){state.quizAnswers=[];$('quiz-modal').classList.add('show');renderQuiz();}function closeQuiz(){$('quiz-modal').classList.remove('show');}function showRecommendation(){const [category,style,moment]=state.quizAnswers;const match=PRODUCTS.find(p=>p.cat===category&&photo(p)&&p.tags?.includes(style)&&p.tags?.includes(moment))||PRODUCTS.find(p=>p.cat===category&&photo(p));$('quiz-card').innerHTML=`<button class="quiz-close" id="close-quiz">×</button><small>RECOMENDACIÓN PARA TI</small><h2>${match?'Hemos encontrado una opción para ti':'Explora el catálogo'}</h2>${match?`<div class="quiz-result"><img src="${encodeURI(photo(match))}" alt="${match.name}"><div><b>${match.brand}</b><p>${match.name}</p><strong>${money(match.price)}</strong></div></div><button class="quiz-result-button" id="view-recommendation">Ver producto</button>`:'<button class="quiz-result-button" id="close-quiz">Volver al catálogo</button>'}`;$('close-quiz').onclick=closeQuiz;const view=$('view-recommendation');if(view)view.onclick=()=>{closeQuiz();openProduct(match.id);};}
function cartLines(){const grouped=state.cart.reduce((all,item)=>{const key=`${item.id}::${item.personalization||''}`;all[key]??={...item,quantity:0};all[key].quantity++;return all;},{});return Object.entries(grouped).map(([key,item])=>({key,product:PRODUCTS.find(p=>p.id===item.id),quantity:item.quantity,personalization:item.personalization,personalizationPrice:item.personalizationPrice||0})).filter(x=>x.product);}function cartTotal(){return state.cart.reduce((total,item)=>total+(PRODUCTS.find(p=>p.id===item.id)?.price||0)+Number(item.personalizationPrice||0),0);}function closePayment(){$('payment-modal').classList.remove('show');}
function renderCart(){const lines=cartLines();$('payment-card').innerHTML=`<button class="payment-close" id="payment-close">×</button><div class="payment-head"><small>MI SELECCIÓN</small><h2>Revisa tu pedido</h2><p>Podrás finalizarlo en el siguiente paso.</p></div><div class="cart-lines">${lines.map(({key,product,quantity,personalization,personalizationPrice})=>`<article class="cart-line"><img src="${encodeURI(photo(product))}" alt=""><div><small>${product.brand}</small><b>${product.name}</b>${personalization?`<em>Grabado: ${escapeHTML(personalization)} · +${money(personalizationPrice)}</em>`:''}<strong>${money(product.price+personalizationPrice)}</strong></div><div class="quantity"><button data-change="-1" data-key="${key}">−</button><span>${quantity}</span><button data-change="1" data-key="${key}">+</button></div></article>`).join('')}</div><div class="payment-total"><span>Total estimado</span><strong>${money(cartTotal())}</strong></div><div class="payment-actions"><button class="payment-secondary" id="continue-shopping">Seguir explorando</button><button class="payment-primary" id="go-payment">Continuar al pago <span>›</span></button></div>`;$('payment-modal').classList.add('show');$('payment-close').onclick=closePayment;$('continue-shopping').onclick=closePayment;$('go-payment').onclick=renderPaymentMethods;$('payment-card').querySelectorAll('.quantity button').forEach(button=>button.onclick=()=>{const [id,personalization='']=button.dataset.key.split('::');const index=state.cart.findIndex(item=>item.id===id&&(item.personalization||'')===personalization);if(button.dataset.change==='1')state.cart.push({id,personalization,personalizationPrice:personalization?PERSONALIZATION_PRICE:0});else if(index>-1)state.cart.splice(index,1);updateCart();state.cart.length?renderCart():closePayment();});}
function renderPaymentMethods(){const total=cartTotal();$('payment-card').innerHTML=`<button class="payment-close" id="payment-close">×</button><div class="payment-head"><small>FINALIZAR COMPRA · 2 DE 2</small><h2>¿Cómo quieres pagar?</h2><p>Selecciona una opción para completar tu selección.</p></div><div class="payment-options"><button class="payment-option" data-method="card"><span class="payment-icon">▣</span><span><b>Tarjeta</b><small>Acerca, inserta o desliza tu tarjeta</small></span><i>›</i></button><button class="payment-option" data-method="counter"><span class="payment-icon">⌑</span><span><b>Pagar en caja</b><small>Muestra este pedido al personal del estanco</small></span><i>›</i></button></div><label class="payment-check"><input type="checkbox" id="payment-confirm"> <span>Confirmo que soy mayor de 18 años y que la compra será validada por el personal del punto de venta.</span></label><div class="payment-total"><span>Total estimado</span><strong>${money(total)}</strong></div><div class="payment-actions"><button class="payment-secondary" id="back-cart">Volver</button><button class="payment-primary" id="confirm-payment" disabled>Confirmar pedido <span>›</span></button></div>`;$('payment-close').onclick=closePayment;$('back-cart').onclick=renderCart;let method='';$('payment-card').querySelectorAll('.payment-option').forEach(option=>option.onclick=()=>{method=option.dataset.method;$('payment-card').querySelectorAll('.payment-option').forEach(x=>x.classList.remove('selected'));option.classList.add('selected');$('confirm-payment').disabled=!$('payment-confirm').checked;});$('payment-confirm').onchange=e=>{$('confirm-payment').disabled=!e.target.checked||!method;};$('confirm-payment').onclick=()=>renderPaymentProcessing(method);}
function renderPaymentProcessing(method){$('payment-card').innerHTML=`<div class="payment-processing"><div class="payment-spinner"></div><small>${method==='card'?'CONECTA CON EL TERMINAL':'PREPARANDO TU PEDIDO'}</small><h2>${method==='card'?'Acerca o inserta tu tarjeta':'Tu selección está lista'}</h2><p>${method==='card'?'Sigue las indicaciones del datáfono para autorizar el pago.':'Presenta el código de pedido al personal del estanco para realizar el pago.'}</p>${method==='counter'?'<strong class="order-code">JTI-'+String(Date.now()).slice(-5)+'</strong>':''}</div>`;setTimeout(()=>renderPaymentSuccess(method),method==='card'?1800:700);}function renderPaymentSuccess(method){const total=cartTotal();$('payment-card').innerHTML=`<div class="payment-success"><div class="success-mark">✓</div><small>PEDIDO REGISTRADO</small><h2>${method==='card'?'Pago autorizado':'Pedido preparado'}</h2><p>${method==='card'?'Tu pago se ha registrado correctamente. Recoge tu selección con el personal del estanco.':'Entrega el código de pedido al personal del estanco para efectuar el pago y recoger tu selección.'}</p><strong>${money(total)}</strong><button class="payment-primary" id="finish-payment">Finalizar</button></div>`;$('finish-payment').onclick=()=>{state.cart=[];updateCart();closePayment();toast('Gracias por tu visita');};}function openCheckout(){if(!state.cart.length){toast('Añade un producto antes de comprar');return;}renderPaymentMethods();}
/* ---------- Salvapantallas de promociones tras inactividad ---------- */
const PROMO_VIDEOS=['Promociones/Publi Camel.mp4','Promociones/publi logic.mp4','Promociones/publi nordic.mp4'];
const IDLE_DELAY=60000;
let idleTimer=null,promoIndex=0;
function resetIdleTimer(){clearTimeout(idleTimer);if(!$('catalogue').hidden&&!$('idle-screen').classList.contains('show'))idleTimer=setTimeout(showIdlePromo,IDLE_DELAY);}
function playPromo(i){const video=$('idle-video');promoIndex=i;video.src=encodeURI(PROMO_VIDEOS[promoIndex]);video.play().catch(()=>{});}
function showIdlePromo(){$('idle-screen').classList.add('show');playPromo(0);}
function hideIdlePromo(){if(!$('idle-screen').classList.contains('show'))return;$('idle-screen').classList.remove('show');const video=$('idle-video');video.pause();video.removeAttribute('src');video.load();resetIdleTimer();}
$('idle-video').addEventListener('ended',()=>playPromo((promoIndex+1)%PROMO_VIDEOS.length));
$('idle-screen').addEventListener('click',hideIdlePromo);
['click','touchstart','keydown','pointerdown'].forEach(evt=>document.addEventListener(evt,resetIdleTimer));
const originalEnterForIdle=enter;enter=()=>{originalEnterForIdle();resetIdleTimer();};
$('age-yes').onclick=enter;$('age-no').onclick=()=>toast('Debes ser mayor de 18 años para continuar');$('brand-home').onclick=()=>{state.category='calentado';state.query='';$('product-search').value='';render();};$('product-search').oninput=e=>{state.query=e.target.value.trim().toLowerCase();render();};$('language-select').onchange=e=>{const english=e.target.value==='en';document.documentElement.lang=e.target.value;const flag=$('language-flag');flag.src=english?'assets/flag-en.png':'assets/flag-es.png';flag.alt=english?'United Kingdom flag':'Bandera de España';toast(english?'Language: English':'Idioma: Español');};$('open-quiz').onclick=openQuiz;$('product-modal').onclick=e=>{if(e.target===$('product-modal'))closeModal();};$('quiz-modal').onclick=e=>{if(e.target===$('quiz-modal'))closeQuiz();};$('payment-modal').onclick=e=>{if(e.target===$('payment-modal'))closePayment();};$('open-cart').onclick=()=>{if(state.cart.length)renderCart();else toast('Tu selección está vacía');};$('buy-button').onclick=openCheckout;
