const state={category:'calentado',cart:[],query:'',quizAnswers:[]};
const icons={calentado:'<svg viewBox="0 0 24 24"><rect x="8" y="9" width="8" height="13" rx="2"/><path d="M10 6c-2-2 1-3 0-5M13 6c-2-2 1-3 0-5M16 6c-2-2 1-3 0-5"/></svg>',vapeo:'<svg viewBox="0 0 24 24"><path d="M9 5h6v4H9zM8 9h8v12H8zM10 13h4M10 18h4"/></svg>',pouches:'<svg viewBox="0 0 24 24"><path d="M4 7l15-2 1 14-15 2zM7 9c3 2 6 2 9 0"/></svg>',cigarrillos:'<svg viewBox="0 0 24 24"><path d="M3 14h16M3 14v4h16v-4M15 14v4M8 10c-2-2 1-3 0-5"/></svg>',accesorios:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M12 3v3M12 18v3M3 12h3M18 12h3M5.6 5.6l2.1 2.1M16.3 16.3l2.1 2.1M18.4 5.6l-2.1 2.1M7.7 16.3l-2.1 2.1"/><circle cx="12" cy="12" r="8"/></svg>'};
const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n||0)+' €';
const photo=(p,color)=>color&&p.imageVariants?.[color]||p.image;
const listed=()=>PRODUCTS.filter(p=>p.cat===state.category&&photo(p)&&(`${p.name} ${p.brand}`).toLowerCase().includes(state.query));
function renderNav(){ $('category-nav').innerHTML=CATEGORIES.map(c=>`<button class="category ${state.category===c.id?'is-active':''}" data-cat="${c.id}"><span>${icons[c.id]}</span><b>${c.name}</b></button>`).join('');$('category-nav').querySelectorAll('button').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;render();}); }
function card(p){return `<article class="product-card" data-id="${p.id}"><div class="product-stage"><div class="stage-copy"><b>${p.brand}</b><span></span><small>${p.cat==='calentado'?'REFINED BY DESIGN':'DESCUBRE LA COLECCIÓN'}</small></div><img src="${encodeURI(photo(p))}" alt="${p.name}"></div><div class="product-info"><small>${p.brand}</small><h3>${p.name}</h3><div><strong>${money(p.price)}</strong><button class="view-product">Ver <i>›</i></button></div></div></article>`;}
function render(){renderNav();const p=listed();$('product-grid').innerHTML=p.length?p.map(card).join(''):'<p class="empty">No hay productos disponibles en esta categoría.</p>';$('product-grid').querySelectorAll('.product-card').forEach(el=>el.onclick=()=>openProduct(el.dataset.id));}
function openProduct(id){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;const first=p.swatches?.[0]||p.color;$('modal-card').innerHTML=`<button class="close" id="close-modal">×</button><div class="modal-visual"><img id="modal-image" src="${encodeURI(photo(p,first))}" alt="${p.name}"></div><div class="modal-info"><small>${p.brand}</small><h2>${p.name}</h2><p>${p.desc}</p><strong>${money(p.price)}</strong>${p.swatches?`<div class="swatches">${p.swatches.map((c,i)=>`<button class="swatch ${i===0?'selected':''}" style="--swatch:${c}" data-color="${c}" aria-label="Color"></button>`).join('')}</div>`:''}<button class="add-button" id="add-product">Añadir a mi selección</button></div>`;$('product-modal').classList.add('show');$('close-modal').onclick=closeModal;$('modal-card').querySelectorAll('.swatch').forEach(s=>s.onclick=()=>{$('modal-card').querySelectorAll('.swatch').forEach(x=>x.classList.remove('selected'));s.classList.add('selected');$('modal-image').src=encodeURI(photo(p,s.dataset.color));});$('add-product').onclick=()=>{state.cart.push({id:p.id});updateCart();closeModal();toast(`${p.name} añadido`);};}
function closeModal(){$('product-modal').classList.remove('show');}function updateCart(){const total=state.cart.reduce((n,i)=>n+(PRODUCTS.find(p=>p.id===i.id)?.price||0),0);$('selection-count').textContent=`${state.cart.length} producto${state.cart.length===1?'':'s'}`;$('cart-total').textContent=money(total);}let timer;function toast(text){const t=$('toast');t.textContent=text;t.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>t.classList.remove('show'),1600);}function enter(){$('age-gate').hidden=true;$('catalogue').hidden=false;render();updateCart();}
const quizSteps=[{question:'¿Qué formato te interesa más?',options:[['Dispositivo de tabaco calentado','calentado'],['Vapeador','vapeo'],['Bolsitas de nicotina','pouches'],['Cigarrillos','cigarrillos']]},{question:'¿Qué estilo buscas?',options:[['Clásico y discreto','clasico'],['Fresco y ligero','fresco'],['Moderno y llamativo','moderno']]},{question:'¿Para qué momento lo buscas?',options:[['Para cualquier momento','cualquier-momento'],['Para una experiencia intensa','intenso'],['Para probar algo nuevo','moderno']]}];
function renderQuiz(step=0){const q=quizSteps[step];$('quiz-card').innerHTML=`<button class="quiz-close" id="close-quiz">×</button><small>PREGUNTA ${step+1} DE ${quizSteps.length}</small><h2>${q.question}</h2><div class="quiz-options">${q.options.map(([label,value])=>`<button data-value="${value}">${label}<span>›</span></button>`).join('')}</div>`;$('close-quiz').onclick=closeQuiz;$('quiz-card').querySelectorAll('.quiz-options button').forEach(b=>b.onclick=()=>{state.quizAnswers[step]=b.dataset.value;if(step<quizSteps.length-1)renderQuiz(step+1);else showRecommendation();});}
function openQuiz(){state.quizAnswers=[];$('quiz-modal').classList.add('show');renderQuiz();}function closeQuiz(){$('quiz-modal').classList.remove('show');}function showRecommendation(){const [category,style,moment]=state.quizAnswers;const match=PRODUCTS.find(p=>p.cat===category&&photo(p)&&p.tags?.includes(style)&&p.tags?.includes(moment))||PRODUCTS.find(p=>p.cat===category&&photo(p));$('quiz-card').innerHTML=`<button class="quiz-close" id="close-quiz">×</button><small>RECOMENDACIÓN PARA TI</small><h2>${match?'Hemos encontrado una opción para ti':'Explora el catálogo'}</h2>${match?`<div class="quiz-result"><img src="${encodeURI(photo(match))}" alt="${match.name}"><div><b>${match.brand}</b><p>${match.name}</p><strong>${money(match.price)}</strong></div></div><button class="quiz-result-button" id="view-recommendation">Ver producto</button>`:'<button class="quiz-result-button" id="close-quiz">Volver al catálogo</button>'}`;$('close-quiz').onclick=closeQuiz;const view=$('view-recommendation');if(view)view.onclick=()=>{closeQuiz();openProduct(match.id);};}
$('age-yes').onclick=enter;$('age-no').onclick=()=>toast('Debes ser mayor de 18 años para continuar');$('brand-home').onclick=()=>{state.category='calentado';state.query='';$('product-search').value='';render();};$('product-search').oninput=e=>{state.query=e.target.value.trim().toLowerCase();render();};$('language-select').onchange=e=>{const english=e.target.value==='en';document.documentElement.lang=e.target.value;const flag=$('language-flag');flag.src=english?'assets/flag-en.png':'assets/flag-es.png';flag.alt=english?'United Kingdom flag':'Bandera de España';toast(english?'Language: English':'Idioma: Español');};$('open-quiz').onclick=openQuiz;$('product-modal').onclick=e=>{if(e.target===$('product-modal'))closeModal();};$('quiz-modal').onclick=e=>{if(e.target===$('quiz-modal'))closeQuiz();};$('open-cart').onclick=()=>toast(state.cart.length?'Tu selección se muestra al personal de caja':'Tu selección está vacía');$('buy-button').onclick=()=>toast(state.cart.length?'Muestra tu selección al personal de caja':'Añade un producto antes de comprar');
